### PR TITLE
update nofp patch

### PR DESCRIPTION
**Pull request by steveklabnik**

### CODE REVIEW

**Comment by phil-opp** [comment]
Thanks! Could you replace

```
+#[cfg(not(disable_float))]
```

with

```
+#[cfg(not(feature = "disable_float"))]
```

? 

Else it's not a _cargo_ feature.

**Comment by phil-opp** [comment]
I'm happy to merge it as is and apply this change myself if you don't have the time...

**Comment by steveklabnik** [comment]
Either is fine: I just literally copied whatever the latest patch by @thepowersgang is. I may not have time to update the PR until tomorrow.

**Comment by phil-opp** [comment]
Ok, then I will do it myself. Thanks for the PR!

**Pull request merged**
